spring:
  datasource:
    url: jdbc:mysql://localhost:3306/SSWAG
    username: root
    password: root
  tomcat:
    max-wait: 20000
    max-active: 50
    max-idle: 20
    min-idle: 15
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        show_sql: true
        id:
          new_generator_mappings: false

server:
  port: 8080
  ssl:
    enabled: true
    key-alias: tomcat
    key-store: "/Users/GOA/.keystore"
    key-store-password: "password"
    key-store-type: "PKCS12"
          
security:
  jwt:
    token:
      secret-key: sswag-secret-key
      expire-length: 36000000
      
UserController:
  signin: Authenticates user and returns its JWT token.
  createUser: Creates user and returns its JWT token
  delete: Deletes specific user by username
  search: Returns specific user by username
  me: Returns current user's data

PatternController:
  approved: Returns approved patterns
  approvedNames: Returns name & id of approved patterns.
  pending: Returns patterns pending approval
  mypending: Returns user submitted pending patterns.
  rejected: Returns rejected patterns
  all: Returns all patterns
  id: Returns specific pattern by id
  approve: Approves a pattern by id
  reject: Rejects a pattern by id
  update: Updates a pattern by id
  delete: Deletes a pattern by id
  new: Creates a new pattern
  save: Saves a pattern

AttachmentController:
  get: Returns attachment by id
  upload: Uploads attachment and returns id
  delete: Deletes attachment by id